client_config_backend: settings
client_config:
  client_id: <YOUR CLIENT_ID>
  client_secret: <YOUR_CLIENT_SECRET>

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
